server:
  port: 9010

spring:
  application:
    name: config-client-apollo

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

# Apollo配置
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://localhost:8080