server:
  port: 7001

spring:
  application:
    name: service-provider

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
